DROP TABLE IF EXISTS "POLL_ENTITY";
DROP TABLE IF EXISTS "POLL_CANDIDATE_LIST_ENTITY";

CREATE TABLE POLL_ENTITY (
  "POLL_INDEX" bigint NOT NULL AUTO_INCREMENT,
  "POLL_CREATED_DATE" varchar(255) DEFAULT NULL,
  "POLL_NAME" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("POLL_INDEX")
);

CREATE TABLE POLL_CANDIDATE_LIST_ENTITY (
  "POLL_CANDIDATE_LIST_INDEX" bigint NOT NULL AUTO_INCREMENT,
  "POLL_CANDIDATE_NAME" varchar(255) DEFAULT NULL,
  "POLL_COUNT" int DEFAULT '0',
  "POLL_INDEX" bigint DEFAULT NULL,
  PRIMARY KEY ("POLL_CANDIDATE_LIST_INDEX"),
  FOREIGN KEY ("POLL_INDEX") REFERENCES POLL_ENTITY ("POLL_INDEX")
);